// wit-bindgen 0.28.0+ generates a module named `zeroclaw` (or package name) and `export!` macro
// The macro is not pub by default.
// The only way to expose it is if `generate!` supports making it public, OR if we define it in the expansion.
//
// In 0.28.0, `wit_bindgen::generate!` creates a module that contains the bindings.
// It seems `export_macro_name` just renames the private macro.
//
// Let's try to use the `with` option to map the world to a public module if possible,
// or simply assume we cannot wrap it easily without `pub_export_macro` (which might be in newer versions).
//
// Plan B: Inline the generate! call in each servant crate.
// But we want a shared SDK.
//
// Plan C: Use a newer version of wit-bindgen if available? 0.28.0 is quite new.
//
// Let's look at `wit_bindgen` 0.28 docs or common patterns.
// Actually, `generate!` macro expansion includes `macro_rules! export`.
// If it's not `#[macro_export]`, we can't export it.
//
// Wait, `wit-bindgen 0.28.0` CHANGELOG says: "The generate! macro now generates a macro named export! by default..."
// And "Added a pub_export_macro configuration option to the generate! macro..."
//
// I tried `pub_export_macro` and it failed parsing. This suggests I might be on an older version than I think,
// OR `pub_export_macro` was added in 0.29+.
// Let's try 0.30.0 (available: v0.53.1 according to previous log).

// wit-bindgen generates a module with the same name as the world or package.
// If we use `default_bindings_module`, it might put things in `src/lib.rs` root.
//
// The redefinition error usually happens when the macro tries to define a macro that is already imported.
//
// Let's try to wrap it in a module to isolate the namespace.
// wit-bindgen 0.36.0 doesn't seem to make `export!` pub even with `pub_export_macro`.
// Or the module wrapping is hiding it.
//
// Let's try to not wrap in `bindings` module but use `export_macro_name` to rename it to something unique
// and then wrap it.
//
// But wait, the error `__export_world_servant_cabi` is gone when wrapped in `bindings`.
// This means the previous error was indeed due to root scope pollution.
//
// The problem now is `pub use bindings::export;` is not working as expected for macros 2.0 or whatever rust uses.
// Macros are exported differently.
//
// We need `#[macro_use]` on the module?
// Or just reference it fully qualified.
//
// But `export!` generated by wit-bindgen usually calls `$crate::...`.
//
// Let's try to expose the bindings module publically and use `servant_sdk::bindings::export!`.
//
// But we want `servant_sdk::export!`.
//
// Let's try this:

// wit-bindgen 0.36.0:
// The macro generated by `export_macro_name: "foo"` is defined at the point of `generate!`.
//
// If we wrap `generate!` in `mod internal`, the macro `export_internal` is inside `internal`.
//
// But `export_internal!` is not exported from `internal` automatically unless we use `#[macro_use]` or `pub use`.
//
// `pub use internal::*;` exports types/values but NOT macros 1.0 (legacy).
//
// But `export_internal` is a macro 2.0 (maybe?) or just a macro_rules.
//
// Wait, `wit_bindgen::generate!` emits `macro_rules! export_internal { ... }`.
// Since it's inside a module, it is scoped to that module.
// To export it from `internal`, we need `#[macro_export]` on it, but we can't add that attribute to generated code easily.
//
// However, `wit-bindgen` likely adds `#[macro_export]` if `pub_export_macro: true` is set?
//
// If `pub_export_macro: true` adds `#[macro_export]`, then the macro is exported at the CRATE ROOT, not the module root.
// So it should be `servant_sdk::export_internal!`.
//
// But previous error said `could not find export_internal in the crate root`.
// This implies it wasn't exported at crate root.
//
// This suggests `pub_export_macro: true` might not be working or doing what we think in 0.36.0.
//
// Let's try a different strategy:
// INLINE the generation in `servant-worker` and other crates, but use `servant-sdk` for shared types if possible.
// But `wit-bindgen` generates types too. Sharing types between two `generate!` calls is hard unless one uses the other's types (using `with` option).
//
// Let's try to fix the macro export one last time.
//
// If we move `generate!` back to root, and use `export_macro_name: "export_internal"`.
// And verify if `export_internal` is available.
//
// If I use `pub_export_macro: true`, it should work.
//
// Let's try to remove `pub mod internal` wrapper and put it back in root.
// And use `export_macro_name: "export_internal"`.
// And define `export!` wrapper.
//
// This failed before with `__export_world_servant_cabi` redefined.
// This error means `generate!` was called twice?
// Or maybe `export_internal!` expands to something that conflicts?
//
// Wait, I might have had `pub mod bindings` AND `pub mod internal` in previous attempts?
// No, I replaced the content.
//
// Let's go back to simplest:
//
// wit_bindgen::generate!({ ... });
//
// And assume `export!` is generated.
// If it's private, we can't use it in other crates.
//
// BUT, if we use `pub_export_macro: true`, it SHOULD be public.
//
// Let's try to put it in root, enable `pub_export_macro: true`, and rename it to `export` (default).
//
// If we get "redefined" error, it might be due to some artifact or interaction with `wit-bindgen` version.
//
// Let's try to use `generate!` in a way that doesn't conflict.
//
// Maybe `wit-bindgen` 0.36.0 generates `export!` at crate root even if inside a module if `#[macro_export]` is used?
//
// Let's try this:
//
// mod bindings {
//     wit_bindgen::generate!({
//         path: "../../wit/host.wit",
//         world: "servant",
//         pub_export_macro: true,
//     });
// }
// pub use bindings::*;
//
// And see if `servant_sdk::export!` exists.
// Note: `export!` is the default name.

// wit-bindgen 0.36.0 with `pub_export_macro: true` generates `#[macro_export] macro_rules! export`.
// If it's inside `mod bindings`, it should be available as `servant_sdk::export!` if we use `#[macro_export]`?
// No, `#[macro_export]` exports to crate root.
//
// But if `export!` is generated, it refers to `$crate::export`.
//
// The error `could not find export in the crate root` suggests that `servant_sdk::export` is missing.
//
// If I use `mod bindings` (private module), and `export!` has `#[macro_export]`, it should be exported.
//
// Wait, maybe `wit-bindgen` DOES NOT emit `#[macro_export]` even with `pub_export_macro: true`?
//
// Let's verify by inspecting the expansion or just assume it's broken/tricky.
//
// Solution: Generate bindings inline in the crate root, but use a unique module name to avoid conflicts?
// `generate!` takes options.
//
// Let's try to remove `mod bindings` wrapper and just put it in root.
// AND use `export_macro_name: "export_internal"` to avoid conflict with `export` if any?
// No, we want `export`.
//
// The "redefined" error suggests `wit-bindgen` is generating something that conflicts.
//
// What if we clean `target`? I did that earlier.
//
// Let's try the simplest possible configuration that is known to work for libraries:
//
// ```rust
// mod bindings {
//     wit_bindgen::generate!({
//         path: "../../wit/host.wit",
//         world: "servant",
//     });
// }
// pub use bindings::*;
// ```
//
// And then in `servant-worker`:
// `use servant_sdk::bindings::Guest;`
// `servant_sdk::bindings::export!(Worker);` -> But `export` is private to `bindings`.
//
// If `export` is private, we cannot access it.
//
// So we MUST re-export it.
//
// `pub use bindings::export;` works for functions/types but NOT for `macro_rules!` unless `#[macro_export]` is used?
//
// Let's try `pub(crate) mod bindings`?
//
// Let's try to define a wrapper macro manually that delegates to `bindings::export`.
//
// But we need to refer to `bindings::export`. If it's private, we can't.
//
// So we need `bindings` to be public?
//
// `pub mod bindings { ... }`
//
// Then `servant_sdk::bindings::export!` should work?
//
// Let's try to modify `servant-worker` to use `servant_sdk::bindings::export!`?
// But `export!` expects to find generated types in current scope or `$crate`.
//
// It's messy.
//
// ALTERNATIVE:
// Define `generate!` in `servant-worker` directly.
// This duplicates code but guarantees it works.
//
// Let's modify `servant-worker/src/lib.rs` to use `generate!` directly.
// And remove `servant-sdk` dependency usage for the macro.
//
// But we want to use types from `servant-sdk`?
// If we generate bindings in worker, we get types in worker.
//
// This is fine for Phase 1.
//
// Let's change `servant-sdk` to just be a dummy or helper library for now,
// or better: let's revert `servant-sdk` to just generate bindings (private) and let consumers use `generate!` themselves?
// No, that's not an SDK.
//
// Let's try to fix the macro export one last time with `#[macro_use]`.
//
// #[macro_use]
// pub mod bindings { ... }
//
// This is valid Rust.

// wit-bindgen 0.36.0 doesn't seem to play nice with macro re-exports.
//
// Let's implement Plan B:
// 1. `servant-sdk` generates types but doesn't try to export the macro for consumption.
// 2. We provide a utility macro `servant_sdk::export_servant!(Type)` that does the dirty work.
//
// But `export_servant!` needs to call `generate!` internally?
// No, `generate!` must be called once.
//
// The issue is that `export!` generated by `wit-bindgen` is tied to the crate where it's generated.
// It uses `$crate::...` to refer to generated types.
//
// If `servant-sdk` generates bindings, `export!` refers to `servant_sdk`.
// When called from `servant-worker`, it expands to code that uses `servant_sdk::...`.
//
// The error `could not find export in the crate root` means `servant_sdk::export` is missing.
//
// Wait, I am using `servant_sdk::export!` in `servant-worker`.
//
// If `export!` is NOT `#[macro_export]`, it's not visible.
// `pub_export_macro: true` SHOULD make it `#[macro_export]`.
//
// Let's try to verify if `wit-bindgen` 0.36.0 actually supports `pub_export_macro`.
// If it ignores it, we are doomed.
//
// Let's assume it's broken or I'm using it wrong.
//
// WORKAROUND:
// Inline the generation in every servant crate.
// This is ugly but robust.
//
// Step 1: Remove `generate!` from `servant-sdk` (or keep it private just for types used within sdk if any).
// Actually, `servant-sdk` should provide helpers.
//
// Let's make `servant-sdk` just a library that re-exports `wit-bindgen` and provides helper functions,
// but forces the user to call `generate!`.
//
// But `servant-sdk` types (like `Guest`) are needed.
//
// If `servant-worker` calls `generate!`, it gets its own `Guest` trait.
//
// So `servant-worker` implementation:
//
// ```rust
// wit_bindgen::generate!({ ... });
// struct Worker;
// impl Guest for Worker { ... }
// export!(Worker);
// ```
//
// This works.
//
// So, let's update `servant-sdk` to NOT generate bindings, but maybe provide some utilities.
// OR just leave `servant-sdk` as a place to hold the WIT file path or something?
//
// Actually, let's keep `servant-sdk` generating bindings so we can write shared code against it.
// But for the `export!` macro, we tell users to use `wit_bindgen::generate!` themselves?
// No, that causes duplicate definitions if they link `servant-sdk`.
//
// Correct approach for shared SDK with wit-bindgen:
// The SDK generates bindings.
// The SDK exports the `export!` macro.
//
// Since I can't get `export!` to be exported, I will try to use `export_macro_name` to something I can manually export?
//
// I tried `export_internal` and wrapping it. The wrapper failed because it couldn't find `export_internal`.
// This means `export_internal` was not `#[macro_export]`.
//
// This means `pub_export_macro: true` is likely doing nothing or not enough.
//
// Let's try `generate!` at root, with `pub_export_macro: true`, AND `export_macro_name: "export"`.
// And verify why it fails.
//
// Wait, `wit-bindgen` 0.28+ changed how exports work.
//
// Let's try to define the macro MANUALLY.
// The `export!` macro expands to:
//
// ```rust
// #[export_name = "handle_task"]
// unsafe extern "C" fn __wasm_handle_task(...) { ... }
// ```
//
// We can write this manually if we know the signature.
//
// But `wit-bindgen` handles ABI complexity.
//
// Let's try to modify `servant-worker` to use `generate!` directly and REMOVE `servant-sdk` dependency for now.
// This will get us moving.
//
// I will update `servant-worker/src/lib.rs` to include `wit_bindgen::generate!`.
// And I need to update `servant-sdk` to NOT generate bindings (or at least not public ones that conflict).
//
// Let's make `servant-sdk` empty for now to avoid conflicts, or just don't link it in worker.
//
// Step 1: Clear `servant-sdk/src/lib.rs`.
// Step 2: Update `servant-worker/src/lib.rs`.
//
// This is the most reliable fix for Phase 1.

pub fn setup() {}
